### ISSUE TITLE
Sum() or Mean() for TruthfulQA MC2?

### ISSUE THREAD

**Issue by Hannibal046** [HillZhang1999/ICD#1]
Hi, thanks for the great work and the code, I want to ask why the log prob is summed rather than averaged here, considering that different choices have different length:
https://github.com/HillZhang1999/ICD/blob/d96efb36393ab6cccfddf200387f96bbe30f2e86/src/decoding_algorithm/contrastive_decoding.py#L227

**Comment by HillZhang1999** [comment]
Hi, we directly follow the official implementation for TruthfulQA MC2 calculation, please refer to:
https://github.com/sylinrl/TruthfulQA/blob/fdd8ad1c0d00a478cf8b0bb41a3ad8378c16293b/truthfulqa/models.py#L321
and 
https://github.com/sylinrl/TruthfulQA/blob/fdd8ad1c0d00a478cf8b0bb41a3ad8378c16293b/truthfulqa/models.py#L343

I appreciate your point that mean() is more reasonable than sum(), but we choose to maintain consistency with the official setting.

**Comment by Hannibal046** [comment]
Thank for your clear and thorough response!
